name = "ft/bafin"
version = "0.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'ft/bafin'"

[repository]
user = "ft"
project = "bafin"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.0.0"
source = "github"

[config]