//CIP113 script hash, never changes
pub const programmable_logic_base_script_hash = "TODO"

//Asset name of the configuration NFT
pub const config_asset_name = "Config"

//Asset name of the global state NFT
pub const global_state_asset_name = "GlobalState"

//Linked list constants (matching v1.2.0 defaults for on-chain compatibility)
pub const linked_list_root_key = #""

pub const linked_list_node_key_prefix = "Node"

pub const linked_list_node_key_prefix_length = 4
